name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.1, 7.4, 8.0, 8.2]

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies on ${{ matrix.php }}
      uses: php-actions/composer@v6
      with:
        php_version: ${{ matrix.php }}
        version: 1
    - name: Execute PHPStan on ${{ matrix.php }}
      uses: php-actions/phpstan@v3
      with:
        path: ./