name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.0, 7.4, 8.0, 8.2]

    steps:
    - uses: actions/checkout@v3
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
    - name: Install dependencies
      run: composer install --dev
    - name: Execute PHP Paralel Lint
      run: vendor/php-parallel-lint/php-parallel-lint/parallel-lint . --exclude vendor